### PR TITLE
Add chain id to init command

### PR DESCRIPTION
**Pull request by dylanschultzie**

### CODE REVIEW

**Comment by ap0calypse644** [comment]
@dylanschultzie This is not really required. The `init` command only generates the directory structure and creates a dummy `genesis.json` file with a random `chain-id`. Passing the `--chain-id` flag to the `init` command simply sets the provided chain-id in this dummy genesis file. In the very next command, we are replacing the dummy genesis file with the proper one from this repo. so, it will be overwritten anyway.

**Comment by dylanschultzie** [comment]
@ap0calypse644 hey, while it's true you give the instructions to replace the genesis with the pre-genesis, there's really no point to doing that if you provide the `chain id` during the init command. It simplifies the gentx process.

**Comment by ap0calypse644** [comment]
@dylanschultzie true. But we have a bunch of vesting and non-vesting genesis accounts in the pre-genesis file. We intend them to be there. They can still be added before collecting all the gentx transactions. However, it opens up room for error when creating the final `genesis.json` file. The reason we provide the pre-genesis is to reduce any room for such human error.

**Comment by dylanschultzie** [comment]
@ap0calypse644 right, but the only information taken from the genesis for a gentx is the chain id and account information, set by add genesis account. 

I would argue the current steps increase the likelihood of error, as you're turning a single necessary step (init chain with chain id) into 2: init chain, then replace genesis.

Having validators download the pregenesis doesn't provide any additional integrity for the vesting accounts.

This isn't a big deal, I'm just trying to save some headache. I'd guess at least one gentx isn't going to use the correct chain id, and will therefore fail the gentx gathering. Setting the chain id alongside init will ensure that doesn't happen.

**Comment by ap0calypse644** [comment]
@dylanschultzie well, can't argue with that! :100: 
Let's make the change! :+1: 

@3eyed-raven Kindly merge

**Review by reeves89 — APPROVED** [review]

**Pull request merged**
